spring.application.name=HotWhellShop-Spring-react.


#config database
##
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/hotwhellshop
spring.datasource.username=root
spring.datasource.password=0362476791
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
##
# config jwt 
hieunumdum.jwt.base64-secret=TRrx3ZoD9xgevlM73MU8/ay9V0+8RJ7NjvFh5Ab0xoTsKzuPYwCOKDZugGYsVxroYRfpP94DH6jBxBhFyBPaQQ==

hieunumdum.jwt.access-token-validity-in-seconds=86400